// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        kotlin_version = '1.9.22'
        threadtracker = '2.1.0'
    }
    repositories {
        google()
        mavenCentral()
        maven {
            url uri('./repositories') //指定本地maven路径
        }
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/rayworks/ThreadTracker")
            credentials {
                username = "${githubUserName}"
                password = "${githubToken}"
            }
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.codoon.threadtracker:threadtracker-plugin:$threadtracker"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        /*maven {
            url uri('../repositories')
        }*/
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/rayworks/ThreadTracker")
            credentials {
                username = "${githubUserName}"
                password = "${githubToken}"
            }
        }
    }

    tasks.withType(Javadoc) {
        options.addStringOption('Xdoclint:none', '-quiet')
        options.addStringOption('encoding', 'UTF-8')
    }

    // lintOptions {
    //     abortOnError false
    // }
    // gradle.taskGraph.whenReady {
    //     tasks.each { task ->
    //         if (task.name == 'mockableAndroidJar') {
    //             task.enabled = false
    //         }
    //     }
    // }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
