apply plugin: 'java-library'
apply plugin: 'groovy'
apply plugin: 'maven-publish'
apply plugin: 'java-gradle-plugin'


java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()

    // 不能太高，以免和用户as或项目冲突
//    implementation 'com.android.tools.build:gradle:4.2.0'
    implementation("com.android.tools.build:gradle-api:8.7.3")
    implementation("org.ow2.asm:asm-util:9.7.1")

    testImplementation 'junit:junit:4.12'
}

repositories {
    mavenCentral()
}

group = 'com.codoon.threadtracker'
version = "$threadtracker"

afterEvaluate {
    publishing {
        publications {
            PluginJava(MavenPublication) {
                from components.java

                groupId = 'com.codoon.threadtracker'
                artifactId = 'threadtracker-plugin'
                version = "$threadtracker"
            }
        }

        repositories {
            maven {
                name = "GitHubPackages"

                url = uri("https://maven.pkg.github.com/rayworks/ThreadTracker")

                credentials {
                    username = "${githubUserName}"
                    password = "${githubToken}"
                }
            }
        }

        /*repositories {
            maven {
                url uri('../repositories')
            }
        }*/
    }
}
